### PR TITLE
increase time out to 5 mins

### PR DESCRIPTION
**Pull request by ycao56**
Signed-off-by: Yu Cao <ycao@redhat.com>

Canary failure: https://github.com/open-cluster-management/backlog/issues/16600
GRC integration test failure: https://app.travis-ci.com/github/open-cluster-management/governance-policy-framework/jobs/540596633#L2473-L2477
Still need to figure out the long term solution for test collision. 

Increasing the time out for now to wait for the iam policy test from GRC-UI to complete. iam policy test from GRC-UI takes around 5 minutes to complete. see https://app.travis-ci.com/github/open-cluster-management/canary/jobs/540539004#L839
Once completed, it should clean up the clusterrolebinding thus this test should pass.

### CODE REVIEW

**Review by mprahl — APPROVED** [review]

**Comment by mprahl** [comment]
@ycao56 could you please add comments in the code explaining why there is such a long timeout?

**Comment by ycao56** [comment]
@mprahl updated

**Comment by mprahl** [comment]
> @mprahl updated

The change didn't come through. Could you please try pushing again?

**Comment by ycao56** [comment]
@mprahl I updated the PR comments but forgot to push.

**Review by mprahl — APPROVED** [review]

**Pull request merged**
